name 'vm'
maintainer 'Torben Knerr'
maintainer_email 'mail@tknerr.de'
license 'MIT'
description 'Installs/Configures a Java Developer VM'
version '0.1.0'

depends 'apt', '2.8.2'
depends 'java', '1.32.0'
depends 'maven', '1.3.0'
depends 'eclipse', '0.1.0'
